import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../assets/img/logo.png'
import over from '../assets/img/1. overview.png'
import ticket from '../assets/img/2. tickets.png'
import idea from '../assets/img/3. ideas.png'
import contact from '../assets/img/4. contacts.png'
import agents from '../assets/img/5. agents.png'
import arts from '../assets/img/6. articles.png'
import sets from '../assets/img/a_1. settings.png'
import subs from '../assets/img/a_2. subscription.png'

export default function View() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Overview</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-slate-100">
                {/* <span
                    className="absolute text-white text-4xl top-5 left-4 cursor-pointer"
                    onclick="openSidebar()"
                    >
                    <i className="bi bi-filter-left px-2 bg-gray-900 rounded-md"></i>
                </span> */}
            <div
                className="sidebar fixed top-0 bottom-0 lg:left-0 p-2 w-[260px] overflow-y-auto text-center bg-gray-900"
            >
                <div className="text-gray-100 text-xl">
                    <div className="p-2.5 mt-1 flex items-center">
                    <Image className="mx-8 w-8" src={logo} alt='' />
                    <h1 className="font-bold text-gray-200 text-[15px] ml-sm">Dashboard Kit</h1>
                    </div>
                </div>
                
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-house-door-fill"></i>
                    <Image className="mx-8 w-4" src={over} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Overview</span>
                </div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={ticket} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Tickets</span>
                </div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={idea} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Ideas</span>
                </div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={contact} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Contacts</span>
                </div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={agents} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Agents</span>
                </div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={arts} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Articles</span>
                </div>
                <div className="my-4 bg-gray-600 h-[1px]"></div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={sets} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Settings</span>
                </div>
                <div
                    className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                >
                    <i className="bi bi-bookmark-fill"></i>
                    <Image className="mx-8 w-4" src={subs} alt='' />
                    <span className="text-[15px] ml-4 text-gray-200 font-bold">Subscription</span>
                </div>
            </div>
            </main>
            
            {/* NavBar PENDIENTE */}

            {/* <body>
                <div className="navbar bg-base-100">
                    <div className="mx-auto">
                        <a className="btn btn-ghost normal-case text-xl">Overview</a>
                    </div>
                    <div className="flex-initial">
                        <div className="dropdown dropdown-end">
                        <label tabIndex={0} className="btn btn-ghost btn-circle">
                            <div className="indicator">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
                            <span className="badge badge-sm indicator-item">8</span>
                            </div>
                        </label>
                        <div tabIndex={0} className="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow">
                            <div className="card-body">
                            <span className="font-bold text-lg">8 Items</span>
                            <span className="text-info">Subtotal: $999</span>
                            <div className="card-actions">
                                <button className="btn btn-primary btn-block">View cart</button>
                            </div>
                            </div>
                        </div>
                        </div>
                        <div className="dropdown dropdown-end">
                        <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
                            <div className="w-10 rounded-full">
                            <img src="https://placeimg.com/80/80/people" />
                            </div>
                        </label>
                        <ul tabIndex={0} className="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                            <li>
                            <a className="justify-between">
                                Profile
                                <span className="badge">New</span>
                            </a>
                            </li>
                            <li><a>Settings</a></li>
                            <li><a>Logout</a></li>
                        </ul>
                        </div>
                    </div>
                </div>
            </body>       */}
        </div>
    )
}

// Di 270 y son 600, en la semana junto 200