import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "../assets/img/logo.png";
import over from "../assets/img/1. overview.png";
import ticket from "../assets/img/2. tickets.png";
import idea from "../assets/img/3. ideas.png";
import contact from "../assets/img/4. contacts.png";
import agents from "../assets/img/5. agents.png";
import arts from "../assets/img/6. articles.png";
import sets from "../assets/img/a_1. settings.png";
import subs from "../assets/img/a_2. subscription.png";

export default function View() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="sidebar fixed top-0 bottom-0 lg:left-0 p-2 w-[260px] overflow-y-auto text-center bg-gray-900">
          <div className="text-gray-100 text-xl">
            <div className="p-2.5 mt-1 flex items-center">
              <Image className="mx-8 w-8" src={logo} alt="" />
              <h1 className="font-bold text-gray-200 text-[15px] ml-sm">
                Dashboard Kit
              </h1>
            </div>
          </div>

          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-house-door-fill"></i>
            <Image className="mx-8 w-4" src={over} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Overview
            </span>
          </div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={ticket} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Tickets
            </span>
          </div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={idea} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Ideas
            </span>
          </div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={contact} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Contacts
            </span>
          </div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={agents} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Agents
            </span>
          </div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={arts} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Articles
            </span>
          </div>
          <div className="my-4 bg-gray-600 h-[1px]"></div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={sets} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Settings
            </span>
          </div>
          <div className="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
            <i className="bi bi-bookmark-fill"></i>
            <Image className="mx-8 w-4" src={subs} alt="" />
            <span className="text-[15px] ml-4 text-gray-200 font-bold">
              Subscription
            </span>
          </div>
        </div>

        <div className="navbar bg-base-100 mx-60">
          <div className="flex-1 mx-auto">
            <a className="btn btn-ghost normal-case text-xl">Overview</a>
          </div>
          <div className="flex-none gap-2 mx-60">
            <div className="form-control">
              <input
                type="text"
                placeholder="Search"
                className="input input-bordered"
              />
            </div>
            <div className="dropdown dropdown-end">
              <label tabIndex={0} className="btn btn-ghost btn-circle avatar">
                <div className="w-10 rounded-full">
                  <img src="https://placeimg.com/80/80/people" />
                </div>
              </label>
              <ul
                tabIndex={0}
                className="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52"
              >
                <li>
                  <a className="justify-between">
                    Profile
                    <span className="badge">New</span>
                  </a>
                </li>
                <li>
                  <a>Settings</a>
                </li>
                <li>
                  <a>Logout</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
